import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
  
[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u005BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
  
[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"
